### ISSUE TITLE
Mounting holes

### ISSUE THREAD

**Issue by JarrettR** [electronut/ElectronutLabs-Bumpy#2]
At least 3, preferably sized for M3 standard fit (3.3mm diameter)

**Comment by electronut** [comment]
For Bumpy? It's meant to be plugged into the USB port, so I don't think mounting holes are useful...

**Comment by JarrettR** [comment]
You still need them for a case!

A case that doesn't have to snap together, that is.

**Comment by electronut** [comment]
OK, maybe for the next version. I was thinking of a press-fit case, actually. Want to keep cost down (~USD 12)  so most people will use it without the case I think. Thanks for the feedback.
